tenants:
  user1:
    jdbcUrl: jdbc:mysql://localhost:3306/user1
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  user2:
    jdbcUrl: jdbc:mysql://localhost:3306/user2
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: password

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: 'true'